/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_penjualan_sederhana;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class Barang extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    
    public Barang() {
        initComponents();
        k.connect();
        refreshtable();
    }
    
    class Brg extends Barang{
        int id_barang, harga;
        String nama_barang, status;
        
        public Brg(){
            this.nama_barang = namabarang_field.getText();
            this.harga = Integer.parseInt(harga_field.getText());
            this.status = status_combo.getSelectedItem().toString();
        }
    }
    
    public void refreshtable(){
        model = new DefaultTableModel();
        model.addColumn("ID Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Status Barang");

        table_barang.setModel(model);

        try{
            this.stat = k.getCon().prepareStatement("Select * from barang");
            this.rs = this.stat.executeQuery();
            while(rs.next()){
                Object[] data = {
                    rs.getInt("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getInt("harga"),
                    rs.getString("status")
            };
            model.addRow(data);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }   
    idbarang_field.setText("");
    namabarang_field.setText("");
    harga_field.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        barang_label = new javax.swing.JLabel();
        logout_button1 = new javax.swing.JButton();
        mtransaksi_button = new javax.swing.JButton();
        idbarang_barang = new javax.swing.JLabel();
        namabarang_barang = new javax.swing.JLabel();
        harga_barang = new javax.swing.JLabel();
        status_barang = new javax.swing.JLabel();
        idbarang_field = new javax.swing.JTextField();
        namabarang_field = new javax.swing.JTextField();
        harga_field = new javax.swing.JTextField();
        status_combo = new javax.swing.JComboBox<>();
        input_button1 = new javax.swing.JButton();
        delete_button1 = new javax.swing.JButton();
        update_button1 = new javax.swing.JButton();
        menuregister_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_barang = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barang_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        barang_label.setText("BARANG");

        logout_button1.setText("Logout");
        logout_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_button1ActionPerformed(evt);
            }
        });

        mtransaksi_button.setText("Menu Transaksi");
        mtransaksi_button.setEnabled(false);
        mtransaksi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtransaksi_buttonActionPerformed(evt);
            }
        });

        idbarang_barang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idbarang_barang.setText("ID Barang");

        namabarang_barang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namabarang_barang.setText("Nama Barang");

        harga_barang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        harga_barang.setText("Harga");

        status_barang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status_barang.setText("Status");

        idbarang_field.setEnabled(false);
        idbarang_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarang_fieldActionPerformed(evt);
            }
        });

        status_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Habis" }));

        input_button1.setText("INPUT");
        input_button1.setEnabled(false);
        input_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_button1ActionPerformed(evt);
            }
        });

        delete_button1.setText("DELETE");
        delete_button1.setEnabled(false);
        delete_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button1ActionPerformed(evt);
            }
        });

        update_button1.setText("UPDATE");
        update_button1.setEnabled(false);
        update_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_button1ActionPerformed(evt);
            }
        });

        menuregister_button.setText("MENU REGISTER");
        menuregister_button.setEnabled(false);
        menuregister_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuregister_buttonActionPerformed(evt);
            }
        });

        table_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_barangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_barang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mtransaksi_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout_button1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga_barang)
                            .addComponent(status_barang))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga_field)
                            .addComponent(status_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namabarang_barang)
                            .addComponent(input_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idbarang_barang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idbarang_field)
                            .addComponent(namabarang_field)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(update_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delete_button1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menuregister_button)))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(barang_label)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mtransaksi_button)
                    .addComponent(logout_button1))
                .addGap(30, 30, 30)
                .addComponent(barang_label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idbarang_barang)
                    .addComponent(idbarang_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namabarang_barang)
                    .addComponent(namabarang_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga_barang)
                    .addComponent(harga_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status_barang)
                    .addComponent(status_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_button1)
                    .addComponent(menuregister_button)
                    .addComponent(delete_button1)
                    .addComponent(update_button1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mtransaksi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtransaksi_buttonActionPerformed
    Transaksi tran = new Transaksi();
    tran.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_mtransaksi_buttonActionPerformed

    private void idbarang_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarang_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbarang_fieldActionPerformed

    private void update_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_button1ActionPerformed
    try{
        Brg b = new Brg();
        this.stat = k.getCon().prepareStatement("update barang set nama_barang=?, "+"harga=?, status=? where id_barang=?");
        stat.setString(1, b.nama_barang);
        stat.setInt(2,b.harga);
        stat.setString(3,b.status);
        stat.setInt(4, Integer.parseInt(idbarang_field.getText()));
        stat.executeUpdate();
        refreshtable();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
}                                            
  
    }//GEN-LAST:event_update_button1ActionPerformed

    private void input_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_button1ActionPerformed
    try{
        Brg b = new Brg();
        this.stat = k.getCon().prepareStatement("insert into barang values(?,?,?,?)");
        stat.setInt(1, 0);
        stat.setString(2,b.nama_barang);
        stat.setInt(3,b.harga);
        stat.setString(4,b.status);
        stat.executeUpdate();
        refreshtable();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    }//GEN-LAST:event_input_button1ActionPerformed

    private void delete_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button1ActionPerformed
        try{
            this.stat = k.getCon().prepareStatement("DELETE FROM barang WHERE id_barang = ?");
            stat.setInt(1, Integer.parseInt(idbarang_field.getText()));
            stat.executeUpdate();
            refreshtable();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_delete_button1ActionPerformed

    private void logout_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_button1ActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_logout_button1ActionPerformed

    private void table_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_barangMouseClicked
    idbarang_field.setText(model.getValueAt(table_barang.getSelectedRow(), 0).toString());
    namabarang_field.setText(model.getValueAt(table_barang.getSelectedRow(), 1).toString());
    harga_field.setText(model.getValueAt(table_barang.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_table_barangMouseClicked

    private void menuregister_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuregister_buttonActionPerformed
    Registrasi reg = new Registrasi();
    reg.setVisible(true);
    this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_menuregister_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barang_label;
    public javax.swing.JButton delete_button1;
    private javax.swing.JLabel harga_barang;
    private javax.swing.JTextField harga_field;
    private javax.swing.JLabel idbarang_barang;
    private javax.swing.JTextField idbarang_field;
    public javax.swing.JButton input_button1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JButton logout_button1;
    public javax.swing.JButton menuregister_button;
    public javax.swing.JButton mtransaksi_button;
    private javax.swing.JLabel namabarang_barang;
    private javax.swing.JTextField namabarang_field;
    private javax.swing.JLabel status_barang;
    private javax.swing.JComboBox<String> status_combo;
    private javax.swing.JTable table_barang;
    public javax.swing.JButton update_button1;
    // End of variables declaration//GEN-END:variables
}
