/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_penjualan_sederhana;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Registrasi extends javax.swing.JFrame {

    /**
     * Creates new form Registrasi
     */
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    public Registrasi() {
        initComponents();
        
        k.connect();
        refreshTable();
    }
    
    class user extends Registrasi{
        int id_user, id_level;
        String username, password, nama_user;
        
    public user(){
        username = username_field.getText();
        password = password_field.getText();
        nama_user = namauser_field.getText();
        id_level = Integer.parseInt(idlevel_combo.getSelectedItem().toString()); ;
    }
}

    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("ID User");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Nama User");
        model.addColumn("ID Level");
        table_registrasi.setModel(model);

        try{
            this.stat = k.getCon().prepareStatement("select * from user");
            this.rs = this.stat.executeQuery();

        while (rs.next()){
            Object[] data ={
                rs.getString("id_user"),
                rs.getString("username"),
                rs.getString("password"),
                rs.getString("nama_user"),
                rs.getString("id_level")
            };
            model.addRow(data);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    iduser_field.setText("");
    username_field.setText("");
    password_field.setText("");
    namauser_field.setText("");
    
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        registrasi_label = new javax.swing.JLabel();
        logout_button2 = new javax.swing.JButton();
        iduser_reg = new javax.swing.JLabel();
        username_reg = new javax.swing.JLabel();
        password_reg = new javax.swing.JLabel();
        namauser_reg = new javax.swing.JLabel();
        idlevel_reg = new javax.swing.JLabel();
        iduser_field = new javax.swing.JTextField();
        username_field = new javax.swing.JTextField();
        password_field = new javax.swing.JTextField();
        namauser_field = new javax.swing.JTextField();
        idlevel_combo = new javax.swing.JComboBox<>();
        input_button2 = new javax.swing.JButton();
        update_button2 = new javax.swing.JButton();
        delete_button2 = new javax.swing.JButton();
        menubarang_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_registrasi = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registrasi_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrasi_label.setText("REGISTRASI");

        logout_button2.setText("Logout");
        logout_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_button2ActionPerformed(evt);
            }
        });

        iduser_reg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iduser_reg.setText("ID User");

        username_reg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_reg.setText("Username");

        password_reg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password_reg.setText("Password");

        namauser_reg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namauser_reg.setText("Nama User");

        idlevel_reg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idlevel_reg.setText("ID Level");

        iduser_field.setEnabled(false);

        idlevel_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        input_button2.setText("INPUT");
        input_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_button2ActionPerformed(evt);
            }
        });

        update_button2.setText("UPDATE");
        update_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_button2ActionPerformed(evt);
            }
        });

        delete_button2.setText("DELETE");
        delete_button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button2ActionPerformed(evt);
            }
        });

        menubarang_button.setText("MENU BARANG");
        menubarang_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubarang_buttonActionPerformed(evt);
            }
        });

        table_registrasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_registrasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_registrasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_registrasi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(username_reg)
                                    .addComponent(password_reg)
                                    .addComponent(namauser_reg)
                                    .addComponent(idlevel_reg)
                                    .addComponent(iduser_reg)
                                    .addComponent(input_button2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(iduser_field)
                                            .addComponent(username_field)
                                            .addComponent(password_field)
                                            .addComponent(namauser_field)
                                            .addComponent(idlevel_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(update_button2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(delete_button2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menubarang_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrasi_label)
                        .addGap(61, 61, 61)
                        .addComponent(logout_button2)
                        .addGap(2, 2, 2)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logout_button2)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(registrasi_label)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iduser_reg)
                    .addComponent(iduser_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_reg)
                    .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_reg)
                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namauser_reg)
                    .addComponent(namauser_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlevel_reg)
                    .addComponent(idlevel_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_button2)
                    .addComponent(menubarang_button)
                    .addComponent(delete_button2)
                    .addComponent(update_button2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_button2ActionPerformed
    try{
        user u = new user();
        this.stat = k.getCon().prepareStatement("insert into user values(?,?,?,?,?)");
        stat.setInt(1, u.id_user);

        stat.setString(2, u.username);
        stat.setString(3, u.password);
        stat.setString(4, u.nama_user);
        stat.setInt(5, u.id_level);
        stat.executeUpdate();
        refreshTable();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_input_button2ActionPerformed

    private void update_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_button2ActionPerformed
        try{
            user u = new user();
            this.stat = k.getCon().prepareStatement("update user set username=?, "
            + "password=?, nama_user=?, id_level=? where id_user=?");
        
        stat.setInt(1, 0);    
        stat.setString(2, u.username);
        stat.setString(3, u.password);
        stat.setString(4, u.nama_user);
        stat.setInt(5, u.id_level);
        stat.executeUpdate();
        refreshTable();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_update_button2ActionPerformed

    private void logout_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_button2ActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_logout_button2ActionPerformed

    private void table_registrasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_registrasiMouseClicked
    iduser_field.setText(model.getValueAt(table_registrasi.getSelectedRow(), 0).toString());
    username_field.setText(model.getValueAt(table_registrasi.getSelectedRow(), 1).toString());
    password_field.setText(model.getValueAt(table_registrasi.getSelectedRow(), 2).toString());
    namauser_field.setText(model.getValueAt(table_registrasi.getSelectedRow(), 3).toString());    // TODO add your handling code here:
    }//GEN-LAST:event_table_registrasiMouseClicked

    private void menubarang_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubarang_buttonActionPerformed
    Barang barang = new Barang();
    barang.setVisible(true);
    this.setVisible(false);
    barang.input_button1.setEnabled(true);
    barang.delete_button1.setEnabled(true);
    barang.update_button1.setEnabled(true);
    barang.menuregister_button.setEnabled(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_menubarang_buttonActionPerformed

    private void delete_button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button2ActionPerformed
    try{
            user u = new user();
            this.stat = k.getCon().prepareStatement("delete from user where id_user=?");
            stat.setInt(1, u.id_user);
            stat.executeUpdate();
            refreshTable();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_delete_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_button2;
    private javax.swing.JComboBox<String> idlevel_combo;
    private javax.swing.JLabel idlevel_reg;
    private javax.swing.JTextField iduser_field;
    private javax.swing.JLabel iduser_reg;
    private javax.swing.JButton input_button2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JButton logout_button2;
    private javax.swing.JButton menubarang_button;
    private javax.swing.JTextField namauser_field;
    private javax.swing.JLabel namauser_reg;
    private javax.swing.JTextField password_field;
    private javax.swing.JLabel password_reg;
    private javax.swing.JLabel registrasi_label;
    private javax.swing.JTable table_registrasi;
    private javax.swing.JButton update_button2;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_reg;
    // End of variables declaration//GEN-END:variables
}
