/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi_penjualan_sederhana;

import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Lenovo
 */
public class Transaksi extends javax.swing.JFrame {
    
    private DefaultTableModel model = null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();
    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        k.connect();
        refreshTable();
        refreshCombo();
    }
    
    class transaksi extends Transaksi{
        int id_transaksi, id_barang, harga, jumlah_beli, total_bayar;
        String nama_pelanggan, tanggal, nama_barang;
        
        public transaksi(){
            this.nama_pelanggan = namapelanggan_field.getText();
            String combo = idbarang_combo.getSelectedItem().toString();
            String[] arr = combo.split(":");
            this.id_barang = Integer.parseInt(arr[0]);
            try{
                Date date = jDateChooser1.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.tanggal = dateformat.format(date);
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.nama_barang = arr[1];
            this.harga = Integer.parseInt(arr[2]);
            this.jumlah_beli = Integer.parseInt(jumlahbeli_field.getText());
            this.total_bayar = this.harga * this.jumlah_beli;
        }
    }
    
    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Pelanggan");
        model.addColumn("ID Barang");
        model.addColumn("Tanggal");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Bayar");
        table_transaksi.setModel(model);
        
        try{
            this.stat = k.getCon().prepareStatement("select * from transaksi");
            this.rs = this.stat.executeQuery();
            while(rs.next()){
                Object[] data ={
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                };
                model.addRow(data);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        idtransaksi_field.setText("");
        namapelanggan_field.setText("");
        jumlahbeli_field.setText("");
        totalbayar_field.setText("");
    }
    
    public void refreshCombo(){
        try{
            this.stat = k.getCon().prepareStatement("select * from barang "
                + "where status='Tersedia'");
            this.rs = this.stat.executeQuery();
            while(rs.next()){
                idbarang_combo.addItem(rs.getString("id_barang")+":"+
                        rs.getString("nama_barang")+":"+rs.getString("harga"));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        transaksi_label = new javax.swing.JLabel();
        logout_button3 = new javax.swing.JButton();
        idtransaksi_tr = new javax.swing.JLabel();
        namapelanggan_tr = new javax.swing.JLabel();
        idbarang_tr = new javax.swing.JLabel();
        tanggal_tr = new javax.swing.JLabel();
        jumlahbeli_tr = new javax.swing.JLabel();
        totalbayar_tr = new javax.swing.JLabel();
        idtransaksi_field = new javax.swing.JTextField();
        namapelanggan_field = new javax.swing.JTextField();
        jumlahbeli_field = new javax.swing.JTextField();
        totalbayar_field = new javax.swing.JTextField();
        idbarang_combo = new javax.swing.JComboBox<>();
        lihatbarang_button = new javax.swing.JButton();
        input_button3 = new javax.swing.JButton();
        update_button3 = new javax.swing.JButton();
        btn_cetak_laporan = new javax.swing.JButton();
        delete_button3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_transaksi = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transaksi_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        transaksi_label.setText("TRANSAKSI");

        logout_button3.setText("Logout");
        logout_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_button3ActionPerformed(evt);
            }
        });

        idtransaksi_tr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idtransaksi_tr.setText("ID Transaksi");

        namapelanggan_tr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namapelanggan_tr.setText("Nama Pelanggan");

        idbarang_tr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idbarang_tr.setText("ID Barang");

        tanggal_tr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tanggal_tr.setText("Tanggal ");

        jumlahbeli_tr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jumlahbeli_tr.setText("Jumlah Beli");

        totalbayar_tr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalbayar_tr.setText("Total Bayar");

        idtransaksi_field.setEnabled(false);
        idtransaksi_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtransaksi_fieldActionPerformed(evt);
            }
        });

        lihatbarang_button.setText("Lihat Barang");
        lihatbarang_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatbarang_buttonActionPerformed(evt);
            }
        });

        input_button3.setText("INPUT");
        input_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_button3ActionPerformed(evt);
            }
        });

        update_button3.setText("UPDATE");
        update_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_button3ActionPerformed(evt);
            }
        });

        btn_cetak_laporan.setText("CETAK LAPORAN");
        btn_cetak_laporan.setEnabled(false);
        btn_cetak_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetak_laporanActionPerformed(evt);
            }
        });

        delete_button3.setText("DELETE");
        delete_button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_button3ActionPerformed(evt);
            }
        });

        table_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_transaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_transaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transaksi_label)
                .addGap(87, 87, 87)
                .addComponent(logout_button3)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namapelanggan_tr)
                                .addComponent(idtransaksi_tr)
                                .addComponent(idbarang_tr)
                                .addComponent(tanggal_tr)
                                .addComponent(jumlahbeli_tr))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalbayar_tr)
                                .addGap(39, 39, 39)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jumlahbeli_field)
                            .addComponent(namapelanggan_field)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idbarang_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lihatbarang_button, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addComponent(idtransaksi_field, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalbayar_field)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(input_button3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update_button3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_button3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cetak_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logout_button3)
                    .addComponent(transaksi_label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idtransaksi_tr)
                    .addComponent(idtransaksi_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namapelanggan_tr)
                    .addComponent(namapelanggan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idbarang_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihatbarang_button)
                    .addComponent(idbarang_tr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tanggal_tr)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahbeli_tr)
                    .addComponent(jumlahbeli_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalbayar_tr)
                    .addComponent(totalbayar_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_button3)
                    .addComponent(input_button3)
                    .addComponent(btn_cetak_laporan)
                    .addComponent(delete_button3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_button3ActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_logout_button3ActionPerformed

    private void idtransaksi_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtransaksi_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtransaksi_fieldActionPerformed

    private void input_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_button3ActionPerformed
    try{
        transaksi tran = new transaksi();
        totalbayar_field.setText(""+tran.total_bayar);
        this.stat = k.getCon().prepareStatement("insert into transaksi values(?,?,?,?,?,?,?,?)");
        this.stat.setInt(1, 0);
        this.stat.setString(2, tran.nama_pelanggan);
        this.stat.setInt(3, tran.id_barang);
        this.stat.setString(4, tran.tanggal);
        this.stat.setString(5, tran.nama_barang);
        this.stat.setInt(6, tran.harga);
        this.stat.setInt(7, tran.jumlah_beli);
        this.stat.setInt(8, tran.total_bayar);
        
        int pilihan = JOptionPane.showConfirmDialog(null,
                "Tanggal: "+tran.tanggal+
                "\nNama Pelanggan: "+tran.nama_pelanggan+
                "\nPembelian: "+tran.jumlah_beli+" "+tran.nama_barang+
                "\nTotal Bayar: "+tran.total_bayar+"\n",
                "Tambahkan Transaksi?",
                JOptionPane.YES_NO_OPTION);
            if(pilihan == JOptionPane.YES_OPTION){
                this.stat.executeUpdate();
                refreshTable();
            }else if(pilihan == JOptionPane.NO_OPTION){
                refreshTable();
            }
            
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_input_button3ActionPerformed

    private void btn_cetak_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetak_laporanActionPerformed
    try{
        File namafile = new File("src/Laporan/Laporan_Transaksi.jasper");
        JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, k.getCon());
         JasperViewer.viewReport(jp, false);
    } catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_cetak_laporanActionPerformed

    private void table_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_transaksiMouseClicked
        idtransaksi_field.setText(model.getValueAt(table_transaksi.getSelectedRow(), 0).toString());
        namapelanggan_field.setText(model.getValueAt(table_transaksi.getSelectedRow(), 1).toString());
        jumlahbeli_field.setText(model.getValueAt(table_transaksi.getSelectedRow(), 6).toString());
        totalbayar_field.setText(model.getValueAt(table_transaksi.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_table_transaksiMouseClicked

    private void update_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_button3ActionPerformed
    try{
            transaksi tran = new transaksi();
            tran.id_transaksi = Integer.parseInt(idtransaksi_field.getText());
            this.stat = k.getCon().prepareStatement("update transaksi set nama_pelanggan=?,"
            + "id_barang=?,tanggal =?,nama_barang=?,harga=?,jumlah_beli=?,total_bayar=? "
            + "where id_transaksi=?");
            this.stat.setString(1, tran.nama_pelanggan);
            this.stat.setInt(2, tran.id_barang);
            this.stat.setString(3, tran.tanggal);
            this.stat.setString(4, tran.nama_barang);
            this.stat.setInt(5, tran.harga);
            this.stat.setInt(6, tran.jumlah_beli);
            this.stat.setInt(7, tran.total_bayar);
            this.stat.setInt(8, tran.id_transaksi);
            this.stat.executeUpdate();
            refreshTable();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_update_button3ActionPerformed

    private void delete_button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_button3ActionPerformed
    try{
        transaksi tran = new transaksi();
        tran.id_transaksi = Integer.parseInt(idtransaksi_field.getText());
        this.stat = k.getCon().prepareStatement("delete from transaksi " + "where id_transaksi=?");
        this.stat.setInt(1, tran.id_transaksi);
        this.stat.executeUpdate();
        refreshTable();
    }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_delete_button3ActionPerformed

    private void lihatbarang_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatbarang_buttonActionPerformed
        Barang brng = new Barang();
        brng.setVisible(true);
        this.setVisible(false);
        brng.input_button1.setEnabled(true);
        brng.delete_button1.setEnabled(true);
        brng.update_button1.setEnabled(true);
        brng.mtransaksi_button.setEnabled(true);
    }//GEN-LAST:event_lihatbarang_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cetak_laporan;
    private javax.swing.JButton delete_button3;
    private javax.swing.JComboBox<String> idbarang_combo;
    private javax.swing.JLabel idbarang_tr;
    private javax.swing.JTextField idtransaksi_field;
    private javax.swing.JLabel idtransaksi_tr;
    private javax.swing.JButton input_button3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlahbeli_field;
    private javax.swing.JLabel jumlahbeli_tr;
    private javax.swing.JButton lihatbarang_button;
    public javax.swing.JButton logout_button3;
    private javax.swing.JTextField namapelanggan_field;
    private javax.swing.JLabel namapelanggan_tr;
    private javax.swing.JTable table_transaksi;
    private javax.swing.JLabel tanggal_tr;
    private javax.swing.JTextField totalbayar_field;
    private javax.swing.JLabel totalbayar_tr;
    private javax.swing.JLabel transaksi_label;
    private javax.swing.JButton update_button3;
    // End of variables declaration//GEN-END:variables
}
